#Profile dev. MySQL Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/silinde_gameaffinity?&useTimezone=true&serverTimezone=UTC
    username: root
    password: 511987
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    spring.datasource.initialization-mode: always
    properties:
        hibernate.enable_lazy_load_no_trans: true
