INSERT INTO genre (name) VALUES ('Action');
INSERT INTO genre (name) VALUES ('Adventure');
INSERT INTO genre (name) VALUES ('Role-Playing');
INSERT INTO genre (name) VALUES ('Simulation');
INSERT INTO genre (name) VALUES ('Sports');
INSERT INTO platform (name, brand) VALUES ('Xbox 360','Microsoft');
INSERT INTO platform (name, brand) VALUES ('PlayStation 3','Sony');
INSERT INTO platform (name, brand) VALUES ('Wii','Nintendo');
INSERT INTO platform (name, brand) VALUES ('Xbox One','Microsoft');
INSERT INTO platform (name, brand) VALUES ('PlayStation 4','Sony');
INSERT INTO platform (name, brand) VALUES ('Wii U','Nintendo');
INSERT INTO developer (name) VALUES ('Atlus');
INSERT INTO developer (name) VALUES ('Bizarre Creations');
INSERT INTO developer (name) VALUES ('Blizzard Entertainment');
INSERT INTO developer (name) VALUES ('Bungie');
INSERT INTO developer (name) VALUES ('Epic Games');
INSERT INTO producer (name) VALUES ('Eiji Aonuma');
INSERT INTO producer (name) VALUES ('Hideo Kojima');
INSERT INTO producer (name) VALUES ('Jonathan Blow');
INSERT INTO producer (name) VALUES ('Gabe Newell');
INSERT INTO producer (name) VALUES ('Yuji Naka');